TRANSACTION_BUSINESS_KEY = ["client_id", "transaction_id"]
DEDUP_ORDER = ["transaction_conversion_date", "ingestion_ts", "source_file"]

SILVER_SCHEMA = """
    client_id                          STRING NOT NULL,
    investiment_id                     STRING,
    transaction_id                     STRING NOT NULL,
    type                               STRING,
    transaction_type                   STRING,
    transaction_type_additional_info   STRING,
    transaction_conversion_date        DATE,
    transaction_quota_price_amount     DECIMAL(20, 2),
    transaction_quota_price_currency   STRING,
    transaction_quota_quantity         DECIMAL(20, 2),
    transaction_value_amount           DECIMAL(20, 2),
    transaction_value_currency         STRING,
    transaction_gross_value_amount     DECIMAL(20, 2),
    transaction_gross_value_currency   STRING,
    income_tax_amount                  DECIMAL(20, 2),
    income_tax_currency                STRING,
    financial_transaction_tax_amount   DECIMAL(20, 2),
    financial_transaction_tax_currency STRING,
    transaction_exit_fee_amount        DECIMAL(20, 2),
    transaction_exit_fee_currency      STRING,
    transaction_net_value_amount       DECIMAL(20, 2),
    transaction_net_value_currency     STRING,
    source_file                        STRING,
    ingestion_ts                       TIMESTAMP,
    ingestion_date                     DATE,
    _rescued_data                      STRING,
    transaction_conversion_month       STRING
"""

SILVER_SCHEMA_REJECTED = """
    client_id                          STRING,
    investiment_id                     STRING,
    transaction_id                     STRING,
    type                               STRING,
    transaction_type                   STRING,
    transaction_type_additional_info   STRING,
    transaction_conversion_date        DATE,
    transaction_quota_price_amount     DECIMAL(20, 2),
    transaction_quota_price_currency   STRING,
    transaction_quota_quantity         DECIMAL(20, 2),
    transaction_value_amount           DECIMAL(20, 2),
    transaction_value_currency         STRING,
    transaction_gross_value_amount     DECIMAL(20, 2),
    transaction_gross_value_currency   STRING,
    income_tax_amount                  DECIMAL(20, 2),
    income_tax_currency                STRING,
    financial_transaction_tax_amount   DECIMAL(20, 2),
    financial_transaction_tax_currency STRING,
    transaction_exit_fee_amount        DECIMAL(20, 2),
    transaction_exit_fee_currency      STRING,
    transaction_net_value_amount       DECIMAL(20, 2),
    transaction_net_value_currency     STRING,
    source_file                        STRING,
    ingestion_ts                       TIMESTAMP,
    ingestion_date                     DATE,
    _rescued_data                      STRING,
    transaction_conversion_month       STRING
"""